server:
  port: 9191
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 50
grpc:
  server:
    port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_belajar_mapping
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: mapping-pool
      maximum-pool-size: 50
      connection-timeout: 30000
      max-lifetime: 600000
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:mysql://localhost:3306/db_belajar_mapping
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    placeholder-replacement: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-idle: 5
          min-idle: 1