server:
  port: 9999
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 50
springdoc:
  baseurl: https://mapping.com
  paths-to-match: /api/v1/**
spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-idle: 5
          min-idle: 1
grpc:
  client:
    integration-server-grpc:
      address: 'static://0.0.0.0:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
mapping:
  hello:
    backend: BE
    backend-function: sayHello